### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (5050,10417) (10416,) (5050,10417)

### ISSUE THREAD

**Issue by JonasLi-19** [zchwang/OnionNet-2#7]
I trained the model (train:4050|val:1000)
my CUDA is 11.8
my python=3.8
scikit-learn = 0.22.1

For more information, as I use pandas to split train|val, the first column is set 'Unnamed: 0' by default.

and the model and scaler and log are generated successfully.
But when I use predict.py, it raises error:

```
Traceback (most recent call last):
  File "predict_pKa.py", line 66, in <module>
    X_test_std = scaler.transform(X_test).reshape([-1] + args.shape)
  File "/root/mambaforge/envs/OnionNet-2/lib/python3.8/site-packages/sklearn/preprocessing/data.py", line 806, in transform
    X -= self.mean
ValueError: operands could not be broadcast together with shapes (5050,10417) (10416,) (5050,10417)
```

However, I find the prediction result generated successfully.....

**Comment by JonasLi-19** [comment]
Oh,, I find there is some of the samples been predicted as '0.000', which means the predict.py has some trouble
